name: Docker Image CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"
env:
  TAG_NAME: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Github container registry
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build and push the Docker image
        env:
          IMAGE_NAME: hauto.device-gateway
        run: |
          VERSION=$(echo $TAG_NAME | sed 's/v//')
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME ghcr.io/${{ github.actor }}/$IMAGE_NAME:$VERSION
          docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:$VERSION